baseURL = "http://localhost:1313/"

title = "Les plantes de Karo"
languageCode = "en-us"
defaultContentLanguage = "en-us"

theme = "axiom"

relativeurls = true
canonifyURLs = false
rssLimit = 100
enableEmoji = true
summaryLength = 40
enableRobotsTXT = true
pluralizelisttitles = false
footnoteReturnLinkContents = "&#8617;"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
post = "/:filename"

[params]
mainSections = ["Balcon", "sejour"]

[params.brand]
domain = ""
email = ""

[params.social]
facebook = "https://www.facebook.com/user_or_page"
github = "https://github.com/user"
instagram = "https://instagram.com/user"
linkedin = "https://www.linkedin.com/in/user"
pinterest = "https://www.pinterest.com/user"
stackoverflow = "https://stackoverflow.com/users/user"
twitter = "https://twitter.com/user"
youtube = "https://www.youtube.com/user"
footer = ["twitter", "github", "instagram"]

[params.services]
analyticsId = "UA-DEV"
adwordsId = "AW-DEV"
adsenseId = "CA-PUB-DEV"
adsenseAdSlotId = "ID-DEV"
adsenseLazy = false
adwordsConversionId = "ID-DEV"
adwordsConversionValue = 0
facebookApp = "FB-DEV"
facebookPixel = "FB-DEV"
disqusUser = "na"

[params.font]
type = ""
path = ""
files = []

[params.image]
width = "2048"
height = "1024"
default = "./image/logo.jpg"
faviconIco = "./image/logo.jpg"
faviconAlt = "./image/logo.jpg"
icon1To1 = "./image/logo.jpg"
icon2To1 = "./image/logo.jpg"
logo = "./image/logo.jpg"

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/CLOUD_NAME/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
autoHeadingID = false
[markup.highlight]
codeFences = false
noClasses = false
tabWidth = 2

[menu]
[[menu.main]]
url = "/Balcon/"
name = "Balcon"
weight = 1

[[menu.main]]
url = "/Intérieur/"
name = "Intérieur"
weight = 1

[[menu.mobile]]
url = "/Balcon/"
name = "Balcon"
weight = 1

[[menu.mobile]]
url = "/info/"
name = "Info"
weight = 2

[[menu.foot]]
url = "/Balcon/"
name = "Balcon"
weight = 2

[[menu.foot]]
url = "/Intérieur/"
name = "Intérieur"
weight = 2

[[menu.foot]]
url = "/info/"
name = "Info"
weight = 3

[languages]
[languages."en-us"]
weight = 1
languageName = "US English"
